services:
  - type: web
    name: keyword-pro-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
